### ISSUE TITLE
Cant find module lib

### ISSUE THREAD

**Issue by kuharan** [robintwhite/pong-ai#1]
Hello, here is an issue with the library

**Followed these steps:**
`conda env create -f pong-ai.yml`
`conda activate pong-ai`
`python play.py`

**Error I got:**
```
(pong-ai) C:\Users\xxxx>python pong.py
Traceback (most recent call last):
  File "pong.py", line 3, in <module>
    from lib.screengrab import screen_record
ModuleNotFoundError: No module named 'lib'
```

What else is needed?

**Comment by robintwhite** [comment]
Hi there,
Thanks for bringing this up. It seems I forgot to upload some of the utility functions. I will do that now. Please check back and try again. Let me know if it works

**Comment by kuharan** [comment]
I pulled your updated code. Now I have a new error. I'll close this issue.
