### ISSUE TITLE
Error on Execution

### ISSUE THREAD

**Issue by kuharan** [robintwhite/pong-ai#2]
**Steps to reproduce:**
C:\Users\xxx\Downloads\pong-ai-master>conda activate pong-ai

(pong-ai) C:\Users\xxx\Downloads\pong-ai-master>python play.py
3
2
1
**Error**
Traceback (most recent call last):
  File "play.py", line 228, in <module>
    comp_paddle, play_paddle = get_paddles(processed_img, factor)
  File "play.py", line 91, in get_paddles
    play_cent = play_conn[3][1:, :][play_conn[2][1:,-1] == play_conn[2][1:,-1].max()] * (1 / factor)
  File "C:\Users\xxx\anaconda3\envs\pong-ai\lib\site-packages\numpy\core\_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by robintwhite** [comment]
Thank you again for looking at this. I am not sure on this error - even when I run it without the game window I don't get this error. Can you screenshot to help me reproduce the error. It might be to do with being unable to find a paddle. You need to make sure the game window is in the correct location. It is set for the top right corner of my screen. You can edit this window position in the code here 
Screen capture position
pos = {"top": 120, "left": 1081, "width": 700, "height": 500}

**Comment by robintwhite** [comment]
I have made a new commit with command line inputs to adjust the capture position, this may require some trial and error to get the position right. I am using a 1920x1080 monitor and positions are in pixels

**Comment by kuharan** [comment]
@robintwhite ok and with a lot of hit and trial I achieved this. But this doesn't run too

![image](https://user-images.githubusercontent.com/22185333/90319029-423fa100-df52-11ea-92ce-52520b2a506d.png)

It shows my desktop background and taskbar with two circles on each side.
The command was - (pong-ai) `C:\Users\xxx\Downloads\pong-ai>python play.py --t=500 --l=500 --width=800 --height=500 --show-frames=False --ai=3`

**Comment by robintwhite** [comment]
Your input for the capture window is not correct, the inputs for me put the window in the top right corner of my monitor. If I assign different values this is what I get. 
![image](https://user-images.githubusercontent.com/20778039/90320210-d9294080-def3-11ea-9ae8-1d0ed8eb238a.png)

**Comment by robintwhite** [comment]
Here is the monitor for the correct positions. If your monitor is a different size or yo have the game window in a different location you need to adjust the input values for the capture window to match where the game is displayed.
![image](https://user-images.githubusercontent.com/20778039/90320236-3f15c800-def4-11ea-8435-d6b05d6a5c8b.png)

**Comment by kuharan** [comment]
Alright, what do you mean when you say correct position?

**Comment by kuharan** [comment]
I made another try with `python play.py --t=100 --l=100 --width=500 --height=500` A window appeared and then I got this -

```
3
2
1
Traceback (most recent call last):
  File "play.py", line 245, in <module>
    play_box = get_play_area(screen) # x, y, w, h
  File "play.py", line 187, in get_play_area
    c = max(contours, key=cv2.contourArea)
ValueError: max() arg is an empty sequence
```

**Comment by robintwhite** [comment]
It cannot find contours that define the play area. Is the capture screen over the game window? Make sure the capture window is as mine is above so that there is a surrounding white border around the game window. If you run 'python process_test.py' you will see the result that needs to be achieved in your game window. You can also see in 'Images' test_img.png which shows the required screen capture image.

**Comment by robintwhite** [comment]
I appreciate the attempt - I did this as a quick option but next time I will make it more robust by having the program find the game area automatically from a full screen capture. A quick trick is to use paint to find the pixel coordinates necessary to type in. ie take a screen capture, open in paint and if you use cropping tool you can see the pixel x,y values in the lower left. The top left position of the game screen is what is needed for the 'top' and 'left' parameters
